### PR TITLE
Update README URLs based on HTTP redirects

### PR DESCRIPTION
**Pull request by ReadmeCritic**
Created with https://github.com/dkhamsing/frankenstein
### GitHub Corrected URLs

| Was | Now |
| --- | --- |
| https://github.com/jaimeiniesta/site_validator | https://github.com/sitevalidator/site_validator |
| https://github.com/sstephenson/rbenv | https://github.com/rbenv/rbenv |
| https://github.com/sstephenson/rbenv-vars | https://github.com/rbenv/rbenv-vars |
### Other Corrected URLs

| Was | Now |
| --- | --- |
| http://gembundler.com | http://bundler.io |
| http://golang.org | https://golang.org/ |
| http://rubygems.org | https://rubygems.org/ |
| http://www.cocoatech.com/pathfinder | http://www.cocoatech.com/pathfinder/ |
| http://www.ruby-lang.org | https://www.ruby-lang.org/ |

### CODE REVIEW

**Comment by bkuhlmann** [comment]
Is there a way to configure Frankenstein to exclude the trailing slashes?

**Comment by ReadmeCritic** [comment]
Not yet :sweat_smile:  although for some of the above, it's http to http`s` that is the bigger change

**Comment by bkuhlmann** [comment]
OK, good to know. Nice gem, wasn't aware of it until now.

I unfortunately, can't merge this PR into the master because of the way the README is auto-generated for this project via the `dots()` function (it's the last function listed in the README). I use `dots()` to rebuild the README based on the links provided within the source code of the bash aliases and functions.

I'm going to close this PR and fix within the source code next based on your observations. In other words, I'm going to apply your changes but in a round-about way. I'll do this shortly.

**Comment by ReadmeCritic** [comment]
Ok, cheers

**Comment by bkuhlmann** [comment]
@ReadmeCritic FYI: Your changes have been applied to master via this [commit](https://github.com/bkuhlmann/dotfiles/commit/9e554e3acc4b05570b1c9510b7407210b5c0367a). The source code has been fixed so future auto-gens of the README will make use of the changes as well. Thanks for detecting these issues.

**Comment by ReadmeCritic** [comment]
:+1:

**Pull request closed without merging**
